function requestPage(){
  const local=(window.HOYWorksStore?.list?.()||[]).slice(0,2);
  return `<section><div class="head"><div class="eyebrow">DEINE ANFRAGEN</div><h1>Nicht lange suchen.</h1><p>HOY Works macht aus einem Problem eine qualifizierte Anfrage: Leistung, Ort, Dringlichkeit, Sprache und Beschreibung.</p></div>${cloudStrip()}<div class="request-launch"><div class="eyebrow">HOY MATCH</div><h3>Was muss erledigt werden?</h3><p>In fünf kurzen Schritten zur passenden lokalen Hilfe. Standort und Gemeinde werden bei GPS-Nutzung gegen offizielle Verwaltungsdaten geprüft.</p><button data-start-request>Neue Anfrage starten</button></div>${signedIn()?`<div class="request-list-live">${state.myRequests.length?state.myRequests.map(requestCard).join(''):'<div class="empty compact"><h2>Noch keine Anfrage.</h2><p>Deine erste echte HOY-Works-Anfrage erscheint hier.</p></div>'}</div>`:`<div class="system-card"><div class="eyebrow">PRIVATER BEREICH</div><h3>Anmelden, um Anfragen wiederzusehen.</h3><div class="system-row"><div><b>E-Mail-Link ohne Passwort</b><small>Deine Anfragen bleiben deinem Konto zugeordnet.</small></div><button class="mini-button" data-auth-open>Anmelden</button></div></div>`}${!signedIn()&&local.length?`<div class="section"><div class="section-head"><h2>Lokaler Testmodus</h2></div>${local.map(r=>`<div class="system-card" style="margin:8px 0 0"><div class="eyebrow">${esc(r.id)}</div><h3>${esc(cat(r.category)?.label||r.category)}</h3><div class="system-row"><div><b>${esc(r.location)}</b><small>${esc(r.description)}</small></div><span class="backend-pill">${esc(r.status)}</span></div></div>`).join('')}</div>`:''}</section>`;
}

function applicationStatus(){return state.providerContext?.applications?.[0]||null}
function provider(){
  const pc=state.providerContext;const app=applicationStatus();const membership=pc?.provider;
  let action='';
  if(!signedIn()) action=`<button data-provider-start>Betrieb anmelden</button>`;
  else if(membership) action=`<button data-business-live>Live-Inbox öffnen</button>`;
  else if(app&&['submitted','reviewing'].includes(app.status)) action=`<button data-provider-start>Angaben ergänzen / weiterer Betrieb</button>`;
  else action=`<button data-provider-start>Betrieb anmelden</button>`;
  return `<section><div class="head"><div class="eyebrow">FÜR BETRIEBE</div><h1>Auf HOY schneller zum passenden Auftrag.</h1><p>Nicht mehr zehn unklare Nachrichten. Eine HOY-Anfrage enthält bereits Leistung, Region, Dringlichkeit und Sprache.</p></div>${cloudStrip()}<div class="partner-hero"><div class="eyebrow">HOY WORKS BUSINESS</div><h2>Erst verstehen. Dann annehmen.</h2><p>Der Betrieb sieht nur passende Leads. Exakte Adresse, Beschreibung und private Fotos werden erst nach einer berechtigten Zuordnung freigegeben.</p>${action}</div>${membership?`<div class="business-grid"><div><b>${pc.open_leads?.length||0}</b><span>PASSENDE LEADS</span></div><div><b>${pc.assigned?.filter(r=>r.status!=='done').length||0}</b><span>IN ARBEIT</span></div><div><b>${pc.assigned?.filter(r=>r.status==='done').length||0}</b><span>ERLEDIGT</span></div></div><div class="system-card"><div class="eyebrow">DEIN BETRIEB</div><h3>${esc(membership.name||'HOY Works')}</h3><div class="system-row"><div><b>Mitgliedsrolle</b><small>${esc(pc.member_role||'operator')}</small></div><span class="backend-pill">AKTIV</span></div></div>`:app?`<div class="system-card"><div class="eyebrow">ANMELDUNG EINGEGANGEN</div><h3>${esc(app.business_name)}</h3><div class="system-row"><div><b>${esc(app.business_email)}</b><small>${esc(dateDE(app.submitted_at))}</small></div><span class="backend-pill ${app.status==='reviewing'?'warn-state':''}">${esc(app.status.toUpperCase())}</span></div><p class="small-copy">Eine Anmeldung macht den Betrieb noch nicht automatisch zum HOY-Partner. Freischaltung und Einsatzgebiet werden separat geprüft.</p></div>`:''}<div class="system-card"><div class="eyebrow">HOY SYSTEMSTATUS</div><h3>Works läuft eigenständig.</h3><div class="system-row"><div><b>HOY Works Supabase</b><small>separates Projekt · Gastro unangetastet</small></div><span class="backend-pill">LIVE</span></div><div class="system-row"><div><b>Offizielle Gemeindeprüfung</b><small>IGN · Cartagena / San Javier</small></div><span class="backend-pill">LIVE</span></div><div class="system-row"><div><b>Private Fotos</b><small>privater Bucket · zeitlich begrenzte Links</small></div><span class="backend-pill">LIVE</span></div><div class="system-row"><div><b>Anbieter-Inbox</b><small>qualifizierte Leads · serverseitig</small></div><span class="backend-pill">LIVE</span></div></div><div class="editorial"><div class="eyebrow">HOY FAMILY</div><h2>Gleiche Marke. Andere Aufgabe.</h2><p>Gastro hilft beim Restaurantmoment. Works hilft beim Problem. Bedienlogik und Vertrauen bleiben HOY.</p><button data-nav="home">Gastansicht ansehen</button></div></section>`;
}

