/* HOY Works 2.4 — third catalogue wave + handyman category */
(function(){
  const extraCategories=[
    {id:'manitas',label:'Kleinreparaturen',short:'Kleinreparaturen',desc:'Kleine Reparaturen, Montage, Handyman',glyph:'⌁'}
  ];
  for(const c of extraCategories){if(!categories.some(x=>x.id===c.id))categories.push(c)}

  const extraProviders=[
    {id:'morelliere',name:'Morellière',cats:['reformas'],area:'La Manga · Cartagena',phone:'+34 606 621 467',languages:['ES'],summary:'Bau- und Reformunternehmen aus Cartagena mit nachgewiesenen Projekten in La Manga, darunter Fassadenarbeiten.',verification:'source_checked',website:'https://www.morelliere.es/',sourceUrl:'https://www.morelliere.es/'},
    {id:'igs-inmoglobal-solutions',name:'I.G.S. Inmoglobal Solutions',cats:['reformas'],area:'La Manga · Cartagena',phone:null,languages:['ES'],summary:'Reformen und Bauprojekte aus Cartagena; die eigene Projektübersicht weist auch Arbeiten in La Manga aus.',verification:'source_checked',website:'https://www.igs-ct.com/',sourceUrl:'https://www.igs-ct.com/'},
    {id:'grupo10-propiedades',name:'Grupo 10 Propiedades',cats:['limpieza','mantenimiento'],area:'La Manga · Cabo de Palos · Cartagena',phone:'+34 630 862 963',languages:['ES'],summary:'Lokaler Anbieter in La Manga mit eigener Reinigungsdivision für Wohnungen, Büros, Gemeinschaften und weitere Flächen.',verification:'source_checked',website:'https://grupo10propiedades.com/',sourceUrl:'https://grupo10propiedades.com/limpieza/'},
    {id:'prime-management-la-manga-club',name:'Prime Management',cats:['mantenimiento','limpieza','manitas'],area:'La Manga Club',phone:'+34 660 129 435',languages:['EN','ES'],summary:'Property Management in La Manga Club mit Inspektionen, Reparaturen, Reinigung sowie Handyman- und Notfallservices.',verification:'source_checked',website:'https://yourprimemanagement.com/',sourceUrl:'https://yourprimemanagement.com/'},
    {id:'resort-sales-management',name:'Resort Sales and Management',cats:['mantenimiento'],area:'La Manga Club',phone:'+34 968 175 117',languages:['ES','EN','DE'],summary:'Seit 1985 in La Manga Club tätiger Property-Management-Anbieter; das eigene Team nennt Spanisch, Englisch und Deutsch ausdrücklich.',verification:'source_checked',website:'https://lamangaclubltd.com/',sourceUrl:'https://lamangaclubltd.com/es/eur/acerca-de-nosotros'},
    {id:'la-manga-diamond',name:'La Manga Diamond',cats:['mantenimiento','limpieza'],area:'La Manga Club',phone:'+34 650 906 047',languages:['EN'],summary:'Familiengeführtes Property Management in La Manga Club mit Betreuung und Wartung von Ferienimmobilien.',verification:'source_checked',website:'https://www.lamangadiamondservices.com/',sourceUrl:'https://www.lamangadiamondservices.com/managementlamangadiamond'},
    {id:'alina-management',name:'Alina Management, Sales & Design',cats:['mantenimiento','limpieza','jardineria','piscina','reformas'],area:'La Manga Club',phone:'+34 605 009 687',languages:['EN','ES'],summary:'Property Management mit Reinigung, Garten-, Pool- und Wartungsservices sowie Reformen und Renovierungen.',verification:'source_checked',website:'https://www.lamangaclubmanagement.com/',sourceUrl:'https://www.lamangaclubmanagement.com/management/'},
    {id:'villa-management-la-manga-club',name:'Villa Management',cats:['mantenimiento','limpieza','reformas','jardineria','piscina'],area:'La Manga Club',phone:'+34 968 175 265',languages:['EN','ES'],summary:'Property Management mit Reinigung, Wartung, Renovierung, Garten- und Poolservice sowie 24-Stunden-Notfallabdeckung.',verification:'source_checked',website:'https://www.vmpropertysales.com/',sourceUrl:'https://www.vmpropertysales.com/management/'},
    {id:'alttamar',name:'Alttamar Servicios La Manga',cats:['mantenimiento','limpieza','jardineria','piscina','manitas'],area:'La Manga · Cabo de Palos',phone:'+34 659 560 375',languages:['ES'],summary:'Haus- und Ferienimmobilienservice mit Reinigung, Garten, Pool, Kleinreparaturen, Schlüsselservice und koordinierten Reparaturen.',verification:'source_checked',website:'https://www.alttamar.es/',sourceUrl:'https://www.alttamar.es/servicios-del-hogar/multiservicios/'},
    {id:'key-care-property-management',name:'Key Care Property Management',cats:['mantenimiento','limpieza','piscina','jardineria','clima','reformas'],area:'La Manga Club · Murcia · Los Alcázares',phone:'+34 711 060 339',languages:['EN'],summary:'Property Management mit Reinigung, Pool-, Garten- und Klimaservice, Notfallreparaturen und Renovierungsprojekten.',verification:'source_checked',website:'https://keycarepropertymanagement.com/',sourceUrl:'https://keycarepropertymanagement.com/'},
    {id:'reparamurcia',name:'ReparaMurcia.com',cats:['electrodomesticos'],area:'La Manga · Cartagena · Mar Menor',phone:null,languages:['ES'],summary:'Mobiler Reparaturservice für Haushaltsgeräte mit ausdrücklich ausgewiesenem Einsatzgebiet La Manga und Mar Menor.',verification:'source_checked',website:'https://www.reparamurcia.com/',sourceUrl:'https://www.reparamurcia.com/'},
    {id:'electricistas-la-manga',name:'Electricistas La Manga',cats:['electricidad'],area:'La Manga · Cartagena',phone:'+34 660 951 468',languages:['ES'],summary:'Elektrofachbetrieb für La Manga und Cartagena; Montage- und Reparaturarbeiten werden auf der eigenen La-Manga-Seite beschrieben.',verification:'source_checked',website:'https://electricistascartagena.pro/electricistas-la-manga/',sourceUrl:'https://electricistascartagena.pro/electricistas-la-manga/'},
    {id:'el-fontanero-cartagena',name:'El Fontanero Cartagena',cats:['fontaneria'],area:'La Manga · Cabo de Palos · Cartagena · San Javier',phone:null,languages:['ES'],summary:'Sanitärbetrieb mit eigener La-Manga-Seite für Reparaturen, Lecks, Verstopfungen und Installationen; Abdeckung bis Veneziola.',verification:'source_checked',website:'https://elfontanerocartagena.com/',sourceUrl:'https://elfontanerocartagena.com/la-manga-del-mar-menor/'},
    {id:'tecniservi',name:'Tecniservi',cats:['electrodomesticos'],area:'La Manga · Cartagena · Mar Menor',phone:'+34 968 392 999',languages:['ES'],summary:'Mobiler Haushaltsgeräte-Service mit ausdrücklich genannter Abdeckung La Manga, Cartagena und Mar Menor.',verification:'source_checked',website:'https://tecniservi.com/',sourceUrl:'https://tecniservi.com/'},
    {id:'reparacion-express-la-manga',name:'Reparación Express La Manga',cats:['electrodomesticos','clima'],area:'La Manga del Mar Menor',phone:null,languages:['ES'],summary:'24-Stunden-Service in La Manga für Haushaltsgeräte; die eigene Seite nennt außerdem Installation und Klimaanlagenservice.',verification:'source_checked',website:'https://lamanga.reparacion-express.com/electrodomesticos-la-manga.html',sourceUrl:'https://lamanga.reparacion-express.com/electrodomesticos-la-manga.html'}
  ];
  for(const p of extraProviders){
    if(!fallbackProviders.some(x=>String(x.id)===String(p.id)))fallbackProviders.push(p);
    if(state.backend!=='online'&&!state.providers.some(x=>String(x.id)===String(p.id)))state.providers.push(p);
  }
})();
